version: '3'

services:
  proxy:
    image: traefik:v2.2
    networks:
      - webgateway
    environment:
      - DO_AUTH_TOKEN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme:/etc/traefik/acme
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`proxy.khayyam.me`)"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.middlewares: auth
      traefik.http.routers.traefik.entrypoints: https
      traefik.http.middlewares.auth.basicauth.users: $HTTP_AUTH
    restart: unless-stopped

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkdock
    networks:
      - webgateway
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    labels:
      traefik.enable: "true"
      traefik.http.routers.jenkins.rule: "Host(`build.khayyam.me`)"
      traefik.http.routers.jenkins.entrypoints: https
      traefik.docker.network: "server_webgateway"
    restart: unless-stopped

networks:
  webgateway:
    driver: bridge

volumes:
  jenkins_home:
