version: '3'

services:
  proxy:
    image: traefik:v2.2
    networks:
      - webgateway
      - logging
    environment:
      - DO_AUTH_TOKEN
      - CF_DNS_API_TOKEN
    ports:
      - "80:80"
      - "443:443"
      - "10022:10022"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme:/etc/traefik/acme
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: 'true'
        fluentd-retry-wait: '1s'
        fluentd-max-retries: '30'
        tag: traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`proxy.khayyam.me`)"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.middlewares: auth
      traefik.http.routers.traefik.entrypoints: https
      traefik.http.middlewares.auth.basicauth.users: $HTTP_AUTH
    restart: unless-stopped

  jenkins:
    build:
      context: .
      dockerfile: jind.dockerfile
    networks:
      - webgateway
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async-connect: 'true'
        fluentd-retry-wait: '1s'
        fluentd-max-retries: '30'
        tag: jenkins
    user: root
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    labels:
      traefik.enable: "true"
      traefik.http.routers.jenkins.rule: "Host(`build.khayyam.me`)"
      traefik.http.routers.jenkins.entrypoints: https
      traefik.docker.network: "server_webgateway"
    restart: unless-stopped

networks:
  webgateway:
    driver: bridge
  logging:
    external:
      name: logging_logging

volumes:
  jenkins_home:
