global:
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  ssh:
    address: :10022

  https:
    address: :443
    http:
      tls:
        certResolver: leresolver
        domains:
          - main: khayyam.me
            sans:
              - "*.khayyam.me"

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false

api:
  dashboard: true

log:
  level: INFO

certificatesResolvers:
  leresolver:
    acme:
      email: khayyam.saleem@gmail.com
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: digitalocean

