debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[api]
dashboard = true

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
            entryPoint = "https"
    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]

[acme]
email = "khayyamsaleem@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
    [acme.dnsChallenge]
    provider = "digitalocean"
    [[acme.domains]]
    main = "*.lifeskillssoftware.tech"
    sans = ["lifeskillssoftware.tech"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "lifeskillssoftware.tech"
exposedByDefault = false
