{
 "title": "Transmission",
 "description": "Transmission statistics prometheus dashboard ",
 "tags": [
  "prometheus",
  "transmission",
  "homelab"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Transmission Instance",
    "query": {
     "query": "label_values(transmission_version,instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(transmission_version,job)"
    }
   },
   {
    "name": "Torrent",
    "query": {
     "query": "label_values(transmission_torrent_ratio,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Session Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of torrents",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(transmission_torrent_done{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Current session upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_uploaded_bytes{instance=~\"$instance\",job=~\"$job\",type=\"current\"}"
    }
   ]
  },
  {
   "title": "1 day upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(transmission_session_stats_uploaded_bytes{instance=~\"$instance\",job=~\"$job\",type=\"cumulative\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "7 days upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(transmission_session_stats_uploaded_bytes{instance=~\"$instance\",job=~\"$job\",type=\"cumulative\"}[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_uploaded_bytes{instance=~\"$instance\",job=~\"$job\",type=\"cumulative\"}"
    }
   ]
  },
  {
   "title": "Current upload speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (transmission_torrent_upload_bytes{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current session ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_uploaded_bytes{instance=~\"$instance\",job=~\"$job\",type=\"current\"}/transmission_session_stats_downloaded_bytes{instance=~\"$instance\",job=~\"$job\",type=\"current\"}"
    }
   ]
  },
  {
   "title": "Overall ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_uploaded_bytes{instance=~\"$instance\",job=~\"$job\",type=\"cumulative\"}/transmission_session_stats_downloaded_bytes{instance=~\"$instance\",job=~\"$job\",type=\"cumulative\"}"
    }
   ]
  },
  {
   "title": "Current session download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_downloaded_bytes{instance=~\"$instance\",job=~\"$job\",type=\"current\"}"
    }
   ]
  },
  {
   "title": "1 day download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(transmission_session_stats_downloaded_bytes{instance=~\"$instance\",job=~\"$job\",type=\"cumulative\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "7 days download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (increase(transmission_session_stats_downloaded_bytes{instance=~\"$instance\",job=~\"$job\",type=\"cumulative\"}[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "transmission_session_stats_downloaded_bytes{instance=~\"$instance\",job=~\"$job\",type=\"cumulative\"}"
    }
   ]
  },
  {
   "title": "Current download speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (transmission_torrent_download_bytes{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload rate / minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max by (name) (transmission_torrent_upload_bytes{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Torrent stats",
   "type": "table",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max by (id, name) (transmission_torrent_ratio{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max by (id, name) (transmission_torrent_files_total{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (name) (avg_over_time (transmission_torrent_seeders{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"}[30d]))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max by (name) (avg_over_time (transmission_torrent_leechers{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"}[30d]))",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max by (id, name) (transmission_torrent_added{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"} * 1000)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max by (id, name) (transmission_torrent_downloads_total{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max by (id, name) (transmission_torrent_peers_connected{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max by (id, name) (transmission_torrent_peers_getting_from_us{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max by (id, name) (transmission_torrent_peers_sending_to_us{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max by (id, name) (transmission_torrent_total_size{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "max by (id, name) (transmission_torrent_uploaded_ever{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Extended statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Torrent stats",
     "type": "table",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "max by (name) (avg_over_time (transmission_torrent_upload_bytes{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"}[30d]))",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "max by (id, name) (transmission_torrent_ratio{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "max by (id, name) (transmission_torrent_files_total{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (name) (avg_over_time (transmission_torrent_seeders{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"}[30d]))",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "max by (name) (avg_over_time (transmission_torrent_leechers{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"}[30d]))",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "max by (id, name) (transmission_torrent_added{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"} * 1000)",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "max by (id, name) (transmission_torrent_downloads_total{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "max by (id, name) (transmission_torrent_upload_bytes{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "max by (name) (avg_over_time (transmission_torrent_upload_bytes{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"}[1d]))",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "max by (id, name) (transmission_torrent_peers_connected{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "max by (id, name) (transmission_torrent_peers_getting_from_us{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "max by (id, name) (transmission_torrent_peers_sending_to_us{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "max by (id, name) (transmission_torrent_total_size{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
       "legendFormat": "{{name}}"
      },
      {
       "expr": "max by (id, name) (transmission_torrent_uploaded_ever{instance=~\"$instance\",job=~\"$job\",name=~\"$Torrent\"})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}