version: '3'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    networks:
      - logging
    depends_on:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    restart: always
  elasticsearch:
    image: elasticsearch:7.6.2
    networks:
      - logging
    expose:
      - 9200
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9200:9200"
    privileged: true
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    restart: always
  kibana:
    image: kibana:7.6.2
    depends_on:
      - elasticsearch
    networks:
      - web
      - logging
    expose:
      - 5601
    labels:
      traefik.enable: "true"
      traefik.http.routers.kibana.rule: "Host(`logs.khayyam.me`)"
      traefik.http.routers.kibana.entrypoints: https
      traefik.http.services.kibana.loadbalancer.server.port: "5601"
      traefik.http.routers.kibana.middlewares: auth
      traefik.http.middlewares.auth.basicauth.users: $HTTP_AUTH
      traefik.docker.network: "server_webgateway"
    restart: always
    
networks:
  logging:
    driver: bridge
  web:
    external:
      name: server_webgateway

volumes:
  elasticsearch:
