receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: jenkins
          metrics_path: /prometheus/
          basic_auth:
            username: ${env:JENKINS_USER}
            password: ${env:JENKINS_PASSWORD}
          scrape_interval: 15s
          static_configs:
            - targets:
                - jenkins:8080

processors:
  transform:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["job"], resource.attributes["service.name"])
          - set(attributes["instance"], resource.attributes["service.instance.id"])

exporters:
  otlphttp:
    metrics_endpoint: http://victoriametrics:8428/opentelemetry/api/v1/push
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [transform]
      exporters: [otlphttp]
