global:
  scrape_interval: 15s
scrape_configs:
- job_name: node-juul
  static_configs:
  - targets:
    - node-exporter:9100
    labels:
      host: juul
- job_name: node-cherryblossom
  static_configs:
  - targets:
    - cherryblossom-docker:9100
    labels:
      host: cherryblossom
- job_name: cadvisor-juul
  static_configs:
  - targets:
    - cadvisor:8080
    labels:
      host: juul
- job_name: cadvisor-cherryblossom
  static_configs:
  - targets:
    - cherryblossom-docker:9101
    labels:
      host: cherryblossom
- job_name: traefik
  static_configs:
  - targets:
    - tailscale:8080
- job_name: jellyfin
  static_configs:
  - targets:
    - cherryblossom-docker:9594
- job_name: ollama-gateway
  metrics_path: /stats/prometheus
  static_configs:
  - targets:
    - cherryblossom-docker:9901
    labels:
      host: cherryblossom
- job_name: transmission
  static_configs:
  - targets:
    - cherryblossom-docker:19091
    labels:
      host: cherryblossom
- job_name: tailscale
  static_configs:
  - targets:
    - tailscale-exporter:9250
- job_name: grafana
  static_configs:
  - targets:
    - grafana:3000
    labels:
      host: juul
- job_name: loki
  static_configs:
  - targets:
    - loki:3100
    labels:
      host: juul
- job_name: dcgm-cherryblossom
  static_configs:
  - targets:
    - cherryblossom-docker:9400
    labels:
      host: cherryblossom
  metric_relabel_configs:
  - action: labeldrop
    regex: Hostname
